# Generated by Django 5.0.2 on 2024-05-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(max_length=45)),
                ('special_key', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Emergencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('login_str', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Recieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_right_now', models.DateTimeField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.controllers')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.emergencies')),
            ],
        ),
        migrations.CreateModel(
            name='Controllers_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.controllers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.users')),
            ],
        ),
    ]
