# Generated by Django 5.0.2 on 2024-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_users_usrpswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tg_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
